version: "3.8"

services:
  app:
    build: .
    container_name: express-app
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
